# Defines a dedicated identity for the application pods within the cluster.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joycrew-service-account
  # Annotations for IAM Roles for Service Accounts (IRSA).
  # This links the Kubernetes service account to an AWS IAM role.
  # ❗️ IMPORTANT: Replace 'YOUR_IAM_ROLE_ARN' with the ARN of the IAM role
  #    that has permissions for S3 and Secrets Manager.
  annotations:
    eks.amazonaws.com/role-arn: "YOUR_IAM_ROLE_ARN"