<<<<<<< HEAD
# ===================================================================
# EKS Cluster Configuration for JoyCrew Backend
# This version is configured to use your EXISTING VPC and subnets.
# ===================================================================
=======
>>>>>>> 12d0498008b5251ba390633e46e4cbf9f1235fd7
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joycrew-cluster
  region: ap-northeast-2
  version: "1.29"

<<<<<<< HEAD
# Enable IAM Roles for Service Accounts (IRSA)
iam:
  withOIDC: true

vpc:
  id: "vpc-067968d8c7f0de694"
  subnets:
    # The worker nodes will be placed in the private subnets.
    private:
      ap-northeast-2b: { id: "subnet-0b1c4ed704fe8809c" }
      ap-northeast-2d: { id: "subnet-00394d1c845cc1187" }
    public:
      ap-northeast-2a: { id: "subnet-03e9e38db1457d819" }
      ap-northeast-2c: { id: "subnet-0283caa043409b846" }

# Configuration for managed node groups
=======
vpc:
  id: "vpc-028bab1adc7ebda69"
  subnets:
    public:
      ap-northeast-2a: { id: subnet-03433c389caba3f2a }
      ap-northeast-2b: { id: subnet-0a1375a0ff65d13b6 }
      ap-northeast-2c: { id: subnet-018b41dd99161e201 }
      ap-northeast-2d: { id: subnet-09e8a18776311c8a4 }

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: joycrew-service-account
        namespace: default
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

>>>>>>> 12d0498008b5251ba390633e46e4cbf9f1235fd7
managedNodeGroups:
  - name: app-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
<<<<<<< HEAD
    maxSize: 4
    # 'privateNetworking' is not needed when subnets are specified above.
    # eksctl will automatically use the private subnets for the nodes.
=======
    maxSize: 3
    privateNetworking: false  # Public 서브넷 사용
>>>>>>> 12d0498008b5251ba390633e46e4cbf9f1235fd7
    ssh:
      allow: true
      publicKeyName: joycrew-deploy-key
    labels:
      role: application
<<<<<<< HEAD
      environment: production
    volumeSize: 20
    volumeType: gp3
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

# Manage essential EKS add-ons
addons:
  - name: vpc-cni
    version: latest
    configurationValues: |-
      enableNetworkPolicy: "true"
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true

# CloudWatch logging configuration
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
=======
>>>>>>> 12d0498008b5251ba390633e46e4cbf9f1235fd7
