apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joycrew-cluster
  region: ap-northeast-2
  version: "1.29"

iam:
  withOIDC: true
  serviceAccounts:
    # 백엔드 파드가 사용할 권한 (AWS 시크릿 매니저 등 접근용)
    - metadata:
        name: joycrew-service-account
        namespace: default
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        # 필요한 경우 S3 접근 권한 등 추가

    # 로드밸런서 컨트롤러가 사용할 권한
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: app-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true # 노드를 프라이빗 서브넷에 배치 (보안 강화)
    ssh:
      allow: true
      publicKeyName: joycrew-deploy-key # AWS EC2 -> 키 페어에 이 이름의 키가 있어야 함!
    labels:
      role: application