apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joycrew-cluster
  region: ap-northeast-2
  version: "1.29"

vpc:
  id: "vpc-028bab1adc7ebda69"
  subnets:
    public:
      ap-northeast-2a: { id: subnet-03433c389caba3f2a }
      ap-northeast-2b: { id: subnet-0a1375a0ff65d13b6 }
      ap-northeast-2c: { id: subnet-018b41dd99161e201 }
      ap-northeast-2d: { id: subnet-09e8a18776311c8a4 }

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: joycrew-service-account
        namespace: default
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: app-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: false  # Public 서브넷 사용
    ssh:
      allow: true
      publicKeyName: joycrew-deploy-key
    labels:
      role: application
