# ===================================================================
# EKS Cluster Configuration for JoyCrew Backend
# This version is configured to use your EXISTING VPC and subnets.
# ===================================================================
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joycrew-cluster
  region: ap-northeast-2
  version: "1.29"

# Enable IAM Roles for Service Accounts (IRSA)
iam:
  withOIDC: true

vpc:
  id: "vpc-067968d8c7f0de694"
  subnets:
    # The worker nodes will be placed in the private subnets.
    private:
      ap-northeast-2b: { id: "subnet-0b1c4ed704fe8809c" }
      ap-northeast-2d: { id: "subnet-00394d1c845cc1187" }
    public:
      ap-northeast-2a: { id: "subnet-03e9e38db1457d819" }
      ap-northeast-2c: { id: "subnet-0283caa043409b846" }

# Configuration for managed node groups
managedNodeGroups:
  - name: app-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    # 'privateNetworking' is not needed when subnets are specified above.
    # eksctl will automatically use the private subnets for the nodes.
    ssh:
      allow: true
      publicKeyName: joycrew-deploy-key
    labels:
      role: application
      environment: production
    volumeSize: 20
    volumeType: gp3
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

# Manage essential EKS add-ons
addons:
  - name: vpc-cni
    version: latest
    configurationValues: |-
      enableNetworkPolicy: "true"
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true

# CloudWatch logging configuration
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler