name: Java Spring Boot CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for Production
        run: |
          chmod +x gradlew
          ./gradlew clean assemble -Pspring.profiles.active=prod

      - name: Locate and Prepare JAR artifact
        id: get_jar_path
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1) 
          
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No executable JAR file found!"
            exit 1
          fi
          echo "jar_path=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Add EC2 Host Key to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEYS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Transfer JAR to EC2 Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ steps.get_jar_path.outputs.jar_path }}
          target: ~/app/build/libs/
          strip_components: 2

      - name: Deploy and Restart Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -eux
            
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"

            echo "Stopping existing JoyCrew backend process..."
            pkill -f 'java -jar' || true

            DEPLOY_DIR="/home/${{ secrets.SSH_USER }}/app/build/libs"
            JAR_NAME=$(basename "${{ steps.get_jar_path.outputs.jar_path }}")

            sudo chmod +x "$DEPLOY_DIR/$JAR_NAME"

            echo "Starting JoyCrew backend application directly with prod profile..."
            nohup /usr/bin/java -jar "$DEPLOY_DIR/$JAR_NAME" --spring.profiles.active=prod > /dev/null 2>&1 &

            sleep 10

            echo "Checking application process status..."
            ps aux | grep "$JAR_NAME" | grep -v grep || true
