name: Java Spring Boot CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for Production
        run: |
          chmod +x gradlew
          ./gradlew clean assemble -Pspring.profiles.active=prod

      - name: Locate and Prepare JAR artifact
        id: get_jar_path
        run: |
          # --- 디버깅용 코드 추가 시작 ---
          echo "Current working directory: $(pwd)"
          echo "Listing contents of build/libs/ before finding JAR:"
          ls -al build/libs/
          # --- 디버깅용 코드 추가 끝 ---

          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No JAR file found!"
            exit 1
          fi
          echo "Found JAR: $JAR_FILE"
          echo "jar_path=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Verify JAR path before transfer
        run: |
          echo "Verifying JAR_FILE path: ${{ steps.get_jar_path.outputs.jar_path }}"
          test -f "${{ steps.get_jar_path.outputs.jar_path }}" || { echo "Error: JAR file not found at expected path!"; exit 1; }
          ls -lh "${{ steps.get_jar_path.outputs.jar_path }}"

      - name: Transfer JAR to EC2 Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ steps.get_jar_path.outputs.jar_path }}
          target: ~/app/build/libs/
          strip_components: 2

      - name: Deploy and Restart Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -eux

            sudo systemctl stop joycrew-backend || true

            DEPLOY_DIR="/home/${{ secrets.SSH_USER }}/app/build/libs"
            JAR_NAME=$(basename "${{ steps.get_jar_path.outputs.jar_path }}")

            sudo chmod +x "$DEPLOY_DIR/$JAR_NAME"

            sudo systemctl start joycrew-backend

            sudo systemctl status joycrew-backend --no-pager || true

      - name: Clean up local SSH key file
        if: always()
        run: rm -f private_key.pem
