name: Java Spring Boot CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for Production
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Locate JAR artifact
        id: get_jar
        run: echo "jar_path=$(find build/libs -name '*.jar')" >> $GITHUB_OUTPUT

      - name: Create environment file
        run: |
          echo "SPRING_PROFILES_ACTIVE=prod" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

      - name: Transfer files to EC2 Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            ${{ steps.get_jar.outputs.jar_path }}
            .env
          target: ~/app/

      - name: Deploy and Restart Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -eux
            
            sudo mkdir -p /etc/joycrew
            sudo mv ~/app/.env /etc/joycrew/.env
            sudo chown joycrew-user:joycrew-group /etc/joycrew/.env
            sudo chmod 600 /etc/joycrew/.env

            JAR_NAME=$(basename "${{ steps.get_jar.outputs.jar_path }}")
            sudo mv ~/app/$JAR_NAME /var/www/joycrew/app.jar

            sudo systemctl restart joycrew-backend
            sudo systemctl status joycrew-backend --no-pager